import { PROMPTS } from './prompts';

export const CONFIG = {
  cloudStorage: {
    bucket: process.env.GCS_BUCKET || 'gen-lang-client-0679842990-vigenair',
    endpointBase: 'https://storage.googleapis.com/storage/v1',
    uploadEndpointBase: 'https://storage.googleapis.com/upload/storage/v1',
    authenticatedEndpointBase: 'https://storage.googleapis.com',
    browsingEndpointBase: 'https://console.cloud.google.com/storage/browser',
    files: {
      subtitles: 'input.vtt',
      analysis: 'analysis.json',
      data: 'data.json',
      presplit: 'presplit_data.json',
      split: '_split.json',
      combos: 'combos.json',
      render: 'render.json',
      approval: 'approval.json',
      formats: {
        square: 'square.txt',
        vertical: 'vertical.txt',
      },
    },
  },
  vertexAi: {
    endpoint: 'aiplatform.googleapis.com',
    projectId: process.env.GCP_PROJECT_ID || 'gen-lang-client-0679842990',
    location: process.env.VERTEX_AI_LOCATION || 'us-central1',
    quotaLimitDelay: 10 * 1000,
    model: process.env.VERTEX_AI_MODEL || 'gemini-2.5-flash',
    modelParams: {
      temperature: 1,
      topP: 1,
      maxOutputTokens: 8192,
      thinkingConfig: { thinkingBudget: 0 },
    },
    generationPrompt: PROMPTS.generationPrompt,
    fullVideoEvaluationPrompt: PROMPTS.fullVideoEvaluationPrompt,
    youtubeIdeasPrompt: PROMPTS.youtubeIdeasPrompt,
    aspectRatioOnlyPrompt: PROMPTS.aspectRatioOnlyPrompt,
    abcdBusinessObjectives: PROMPTS.abcdBusinessObjectives,
    textAssetsGenerationPrompt: PROMPTS.textAssetsGenerationPrompt,
    textAssetsBadExamplePromptPart: PROMPTS.textAssetsBadExamplePromptPart,
  },
  defaultVideoLanguage: 'English',
  defaultVideoWidth: 1280,
  defaultVideoHeight: 720,
  defaultVideoDurationStep: 5,
  videoFolderNameSeparator: '--',
  videoFolderNoAudioSuffix: 'n',
  videoIntelligenceConfidenceThreshold: 0.7,
  defaultTranscriptionService: 'whisper',
  defaultCacheExpiration: 60,
  defaultDuration: 30,
  retryDelay: 6000,
  maxRetries: 600,
  maxRetriesAppsScript: 5,
  debug: true,
};
