export interface MasterSystemSection {
  number: string;
  id: string;
  title: string;
  category: 'Foundation' | 'Tokens' | 'Components' | 'Patterns' | 'Guidelines' | 'Governance';
  status: 'approved' | 'locked' | 'foundation' | 'roadmap';
  version: string;
  description: string;
  componentRef?: string;
  approvedRules?: string[];
}

export const MASTER_VISUAL_SYSTEM_SECTIONS: MasterSystemSection[] = [
  {
    number: '01',
    id: 'brand-foundation',
    title: 'Brand Foundation',
    category: 'Foundation',
    status: 'approved',
    version: 'v1.0',
    description: 'WPP Open alignment, core ethos ("Recognizably WPP. Distinctly Media Solutions"), asset heritage, and Product & Brand Hierarchy specification.',
    componentRef: 'brand-foundation',
    approvedRules: [
      'WPP Open Ecosystem Alignment: WPP first (#000050). Media Solutions second (#AEF366). Creative Intelligence third. WPP Open provides ecosystem belonging; Media Solutions provides product expression; Creative Intelligence provides solution identity.',
      'Primary Structural Color: WPP Navy (#000050) replaces black as the primary structural UI color for main navigation, sidebars, structural headers, important titles, and high-level product framing.',
      'Black Usage: Black (#000000 / neutral.900/1000) is reserved primarily for running text, editorial body copy, and content where maximum neutral contrast is appropriate. Black is not used as the default for sidebars, navigation, or large structural framing.',
      'Media Solutions Distinction: Media Solutions Signature Lime (#AEF366) is an intentional product distinction, used selectively for Creative Intelligence identity, active indicators, selected states, highlights, and intelligence moments.',
      'Hierarchy: WPP Media Solutions LATAM → Creative Services LATAM → Creative Intelligence → Social / YouTube',
      'Reusable Brand Lockup: [ WPP Media Solutions ] / [ Creative Intelligence ] / [ Application ] centered on a single shared horizontal optical axis',
      'Client Brand Compatibility: Media Solutions products act as a neutral intelligence canvas; client content and branding remain the hero',
      'Typographic expression over logo stacking; logos are not mandatory at every level',
      'Header Master consumes hierarchy as configurable contextual slots (brand, businessUnit, productFamily, product)',
    ],
  },
  {
    number: '02',
    id: 'color-system',
    title: 'Color System',
    category: 'Tokens',
    status: 'approved',
    version: 'v1.0',
    description: 'WPP Open aligned color specification: WPP Navy (#000050) primary structure, White & Neutral surfaces, WPP Blue (#5967F6), Media Solutions Lime (#AEF366), Supporting Violet (#7D72E8), and Semantic signals.',
    componentRef: 'color-validation-board',
    approvedRules: [
      '6-Tier Conceptual Color Hierarchy: 1. WPP Navy (Primary structural / brand color #000050) → 2. White & neutral surfaces (Primary interface environment) → 3. WPP Blue (#5967F6 interaction & telemetry) → 4. Media Solutions Lime (#AEF366 distinctive product accent) → 5. Violet (#7D72E8 intelligence & AI) → 6. Semantic colors (Success, Warning, Error)',
      'Primary Structural Color: WPP Navy (#000050) replaces black as the default structural color across sidebars, headers, main navigation, navigation states, and high-level UI framing',
      'Predominantly Light Interface: Canvas is light, spacious, and clean, with white content surfaces and soft neutral backgrounds inspired by WPP Open visual language',
      'Dark Contexts Evolution: Dark contextual environments now use WPP Navy (#000050) rather than Black (#000000) for intelligence experiences, featured dark sections, product identity moments, and dark analytical compositions. No separate "black mode"',
      'Black Discipline: Black (#000000) is reserved for running text and editorial body copy, not structural surfaces',
      'Lime Discipline: Signature Lime (#AEF366) is used selectively for active indicators, selected states, small highlights, intelligence moments, and product accents (zero dominant background floods, never a generic success color)',
      'Supporting Blue for information, navigation, active telemetry, and global focus ring; Supporting Violet for AI, machine intelligence, and deep analytics',
      'Black and gray are structural neutrals, never data colors',
      'Strict WCAG 2.1 AA/AAA compliance against neutral surfaces',
    ],
  },
  {
    number: '03',
    id: 'typography-system',
    title: 'Typography System',
    category: 'Foundation',
    status: 'approved',
    version: 'v1.0',
    description: 'Frozen v1.0 typography specification covering the custom WPP typeface across Editorial, Product UI, Data, and Presentation roles, updated for WPP Navy heading expression.',
    componentRef: 'typography-calibration-board',
    approvedRules: [
      'WPP Navy Heading Expression: Titles and important headings preferentially use WPP Navy (#000050) rather than Black, establishing ecosystem belonging while maintaining approved weights, scale, and hierarchy',
      'WPP Typographic Character: Spacious, light, editorial, intelligent, and controlled. Font weights are not artificially increased because color has changed',
      'Exclusive usage of local WPP typeface (WOFF2 format, 5 weights: Light, Regular, Medium, Bold, Black)',
      'Editorial, Product UI, Data/Telemetry, and Presentation functional roles',
      'Fluid typographic scale with optical tracking calibrations',
      'Mono numerals (tabular lining) for analytical and financial metrics',
      'Global Capitalization Standard: Sentence case is the default across all UI copy. Title Case is strictly prohibited for general UI copy (page titles, section headings, card titles, navigation items, tabs, buttons, labels, form fields, metrics, status labels, tooltips, empty states, messages).',
      'Capitalization Exceptions: Official capitalization is strictly preserved for brand names, company names, product names, platform names, official solution names, acronyms, and proper nouns (e.g. WPP Media, Creative Intelligence, Meta, YouTube, AI).',
    ],
  },
  {
    number: '04',
    id: 'spacing-layout',
    title: 'Spacing & Layout',
    category: 'Foundation',
    status: 'approved',
    version: 'v1.0',
    description: 'Frozen v1.0 spatial architecture: 4px base scale, component padding densities, page containers, 12-column responsive grid, and vertical rhythm.',
    componentRef: 'spacing-calibration-board',
    approvedRules: [
      'Strict 4px geometric progression (4, 8, 12, 16, 20, 24, 32, 40, 48, 64px)',
      'Standard, Comfortable, and Dense spatial modes',
      '12-column responsive fluid grid with 16/24px gutters',
      'Zero arbitrary pixel margins or ad-hoc vertical offsets',
    ],
  },
  {
    number: '05',
    id: 'core-components',
    title: 'Core Components',
    category: 'Components',
    status: 'approved',
    version: 'v1.0',
    description: 'Frozen v1.0 component library: Button (pill), Icon Button (structured), Input, Select, Checkbox, Radio, Toggle, Tag (pill), Status Badge (pill), Tabs, and Tooltip.',
    componentRef: 'core-components-board',
    approvedRules: [
      'Buttons use full pill geometry; Icon buttons use structured 8px rounded squares',
      'Tags describe taxonomy with neutral/supporting tints; Status badges communicate operational state',
      'All interactive controls adhere to the global Blue/Violet focus ring',
      'Zero decorative pills or unnecessary interactive chrome',
    ],
  },
  {
    number: '06',
    id: 'card-system',
    title: 'Card System',
    category: 'Components',
    status: 'locked',
    version: 'v1.0',
    description: 'Frozen container architecture: Surface contrast first, Border second, Shadow last. No decorative shadows, no default grey outlines, functional borders, metric/insight/recommendation/media cards, expandable states, and composition.',
    componentRef: 'card-system-board',
    approvedRules: [
      'Core Philosophy: Surface contrast first. Border second. Shadow last. A component does not require a border or shadow simply to communicate container status.',
      'A Card is a Container, Not Automatically an Elevated Object: Visual definition comes from content grouping, spacing, surface contrast, typography, and position.',
      'No Decorative Shadows: Standard product surfaces must default to box-shadow: none. Shadows are strictly reserved for true floating/transient overlays (dropdowns, popovers, tooltips, modals, menus).',
      'No Default Grey Outlines: Standard product surfaces do not automatically receive visible grey borders when background surface contrast is optically sufficient.',
      'Border as Function, Not Decoration: Borders communicate focus, selection, active state, structural separation where contrast alone is insufficient, error/warning/semantic state, or special visual treatment.',
      'Special Visual Treatments: Contextual gradient borders (e.g. Lime → Blue → Violet) may communicate active intelligence / process states; never applied repetitively to standard cards.',
      'Standardized surface contexts: Light, Dark (WPP Navy #000050), and Featured (dark olive)',
      'Overlay media card treatment for vertical 9:16 and social media assets',
      'Resilient content overflow handling (clamp with tooltip or expand)',
      'Approved card footer actions and action hierarchy',
      'Not Everything Needs to Be a Card: Content thrives when permitted to exist as open page-level compositions, editorial surfaces, atmospheric environments, and media-led narratives rather than forcing every element into a bounded container',
      'Page Canvas vs Component Surface: Page canvas hosts broad atmosphere and editorial flow; Component surface hosts scoped data, interactions, and controls',
    ],
  },
  {
    number: '07',
    id: 'dataviz-system',
    title: 'Data Visualization System',
    category: 'Components',
    status: 'approved',
    version: 'v1.0',
    description: 'Frozen v1.0 data visualization language: visual principles, data hierarchy, gradient language, no black/gray as data, subtle axes/grids, and WPP Navy structural elements.',
    componentRef: 'dataviz',
    approvedRules: [
      'Black and gray are structural colors, never data colors',
      'WPP Navy (#000050) Structural Chart Usage: WPP Navy may be used for structural chart elements, labels, axes, reference elements, and supporting UI structure. WPP Navy is never turned into a generic data series color',
      'Primary single series uses Blue (#5967F6) or Blue → Violet progression',
      'Media Solutions Lime (#AEF366) used for approved highlight metrics and key threshold endpoints',
      'Gradients communicate progression or intelligence, never decoration',
      'Subdued neutral gridlines and axes (#E6E6E5 / dark:border-white/10)',
    ],
  },
  {
    number: '08',
    id: 'navigation-forms',
    title: 'Navigation & Forms',
    category: 'Components',
    status: 'locked',
    version: 'v1.0',
    description: 'Frozen v1.0 navigation and forms language: WPP Navy (#000050) structural navigation, active Blue → Violet gradient, global focus ring, form hierarchy, multi-select, and file upload.',
    componentRef: 'navigation-forms',
    approvedRules: [
      'Product Shell: Global Top Header + Product Sidebar (WPP Navy #000050 structural identity) + Content Canvas (Light, spacious, white surfaces)',
      'Primary Structural Color: Main navigation, sidebars, and structural headers use WPP Navy (#000050) instead of black',
      'Navigation uses color to communicate location, not decoration',
      'Active navigation item uses the approved Blue → Violet gradient or Lime indicator pip',
      'Global focus ring: 2px Blue/Violet ring (focus.ring), zero black outline',
      'Form fields are neutral by default with restrained multi-select and file drop zones',
    ],
  },
  {
    number: '09',
    id: 'product-patterns',
    title: 'Product Patterns',
    category: 'Patterns',
    status: 'locked',
    version: 'v1.0',
    description: 'Frozen v1.0 reusable compositions: Product Dashboard, Client Report, Search & Results, Filtered Data View, Detail/Analysis, Creation Flow, Review/Approval, Insight Exploration, Recommendation, and Report/Export.',
    componentRef: 'product-patterns',
    approvedRules: [
      'Hierarchy: Component → Product Pattern → Product Application',
      'Dashboard Surface Pattern: Default standard surfaces use white / approved light surfaces (#FFFFFF) on neutral page canvas (#F8F8F7), no shadow (box-shadow: none), no decorative grey outline. Dashboards may use an intentional special gradient border (Lime → Blue → Violet) for active intelligence/process containers.',
      'Report Surface Pattern: Client Reports avoid turning every section into an elevated card. Employs page-level composition, surface contrast, whitespace spacing, editorial hierarchy, and selective containers. Standard report surfaces never use automatic shadows or grey outlines.',
      'Content-first composition prioritizing user goals before visual decoration',
      'Narrative Visual Hierarchy: Primary Story → Supporting Evidence → Context → Action before containerization or decorative chrome',
      'Detail/Analysis Pattern 04 calibrated single-series Blue → Violet progression',
      'Inter-pattern journey transitions (e.g. Dashboard → Detail → Report)',
    ],
  },
  {
    number: '10',
    id: 'surface-context',
    title: 'Surface Context',
    category: 'Foundation',
    status: 'foundation',
    version: 'v1.0',
    description: 'Multi-surface rendering rules across Light (#FFFFFF / #F8F8F7) canvas and WPP Navy (#000050) contextual dark environments, governed by Surface Contrast First.',
    approvedRules: [
      'Universal Principle: Surface contrast first. Border second. Shadow last. No decorative shadow. No automatic grey outline. No unnecessary elevation.',
      '4-Step Design Decision Hierarchy: 1. Can spacing establish relationship? → 2. Can surface contrast establish relationship? → 3. Is a border actually necessary? → 4. Is elevation actually necessary? If no, do not add the treatment.',
      'AI Guardrail: Do not add shadows or grey borders by default to make containers feel finished or structured. Do not turn every content group into an elevated card. Prefer surface contrast, spacing, and composition before borders or elevation.',
      'Tokens adaptively resolve based on surface context',
      'WPP Navy as Default Dark Context: Dark contextual environments now use WPP Navy (#000050) rather than Black (#000000/#171717) for intelligence experiences, featured dark sections, product identity moments, and dark analytical compositions',
      'No Separate Black Mode: Dark is an intentional contextual composition for deep analytics and immersive moments, NOT a global product theme or black mode',
      'Primary Environment is Light & Spacious: White content surfaces, soft neutral canvas (#F8F8F7), and restrained hairline dividers (#E6E6E5) aligned with WPP Open visual language',
      'Text contrast ratios maintain WCAG 2.1 AA/AAA compliance across all contexts',
    ],
  },
  {
    number: '11',
    id: 'layout-grid',
    title: 'Layout & Grid',
    category: 'Foundation',
    status: 'foundation',
    version: 'v1.0',
    description: 'Responsive canvas geometry: 12-column grid, responsive breakpoints, max-width constraints, margins, gutters, and asymmetric split layouts.',
    approvedRules: [
      'Desktop: 12 columns, 24px gutters, max-width 1600px',
      'Tablet: 8 columns, 16px gutters, max-width 1024px',
      'Mobile: 4 columns, 12px gutters, 100% fluid reflow',
    ],
  },
  {
    number: '12',
    id: 'states-feedback',
    title: 'States & Feedback',
    category: 'Guidelines',
    status: 'foundation',
    version: 'v1.0',
    description: 'Unified state machine specifications: Default, Hover, Focus, Active, Disabled, Loading, Empty, Error, Success, and Partial.',
    approvedRules: [
      'Interactive controls maintain visually distinct states',
      'Focus state applies global Blue/Violet focus.ring',
      'Loading states use shimmer skeletons adhering to component geometry',
    ],
  },
  {
    number: '13',
    id: 'responsive',
    title: 'Responsive Behavior',
    category: 'Guidelines',
    status: 'foundation',
    version: 'v1.0',
    description: 'Adaptive design patterns: Reflow, Stack, Collapse, Transform, and Progressive Disclosure across viewports down to 320px.',
    approvedRules: [
      'Zero horizontal scrollbar regressions on mobile viewports',
      'Minimum touch targets of 44x44px preserved on mobile devices',
      'Multi-column cards collapse gracefully to single column stacks',
    ],
  },
  {
    number: '14',
    id: 'motion',
    title: 'Motion & Animation',
    category: 'Guidelines',
    status: 'roadmap',
    version: 'v1.0',
    description: 'Choreography principles, easing curves, timing tokens, and reduced-motion accessibility guidelines.',
    approvedRules: [
      'Functional transition durations: 150ms (micro), 250ms (standard), 350ms (structural)',
      'Subtle cubic-bezier easing avoiding bouncing or playful cartoon physics',
      'Strict prefers-reduced-motion media query respect',
    ],
  },
  {
    number: '15',
    id: 'accessibility',
    title: 'Accessibility & A11y',
    category: 'Governance',
    status: 'foundation',
    version: 'v1.0',
    description: 'WCAG 2.1 Level AA conformance, keyboard navigation pathways, screen reader ARIA landmarks, and focus management.',
    approvedRules: [
      '4.5:1 minimum text contrast ratio against background surfaces',
      'Non-text contrast of 3:1 for interactive component boundaries and states',
      'Visible, non-black focus indicator on all keyboard-navigable elements',
    ],
  },
  {
    number: '16',
    id: 'content-ux',
    title: 'Content & UX Writing',
    category: 'Guidelines',
    status: 'approved',
    version: 'v1.0',
    description: 'Tone of voice, editorial terminology, metric labeling conventions, error message formulas, microcopy standards, and global capitalization rules.',
    approvedRules: [
      'Global Capitalization Standard: Sentence case is the default across all UI copy. Title Case is strictly prohibited for general UI copy.',
      'Scope of Application: Page titles, section headings, card titles, navigation items, tabs, buttons, labels, form fields, metrics, status labels, supporting UI copy, product interface copy, empty states, tooltips, messages, and notifications.',
      'Preserved Exceptions: Official capitalization must be preserved for brand names, company names, product names, platform names, official solution names, acronyms, and proper nouns (e.g. WPP Media, Creative Intelligence, Meta, YouTube, AI).',
      'Examples: Use "Creative Intelligence dashboard" (not "Creative Intelligence Dashboard"), "Progreso del análisis" (not "Progreso Del Análisis"), "View all results" (not "View All Results"), "Explore creative" (not "Explore Creative").',
      'Clear, direct, intelligent, and human tone with concise label verbs on primary action triggers.',
      'Explanatory tooltips for complex domain calculations and abbreviations.',
    ],
  },
  {
    number: '17',
    id: 'special-treatments',
    title: 'Special Visual Treatments — Atmospheric Backgrounds',
    category: 'Guidelines',
    status: 'approved',
    version: 'v1.0',
    description: 'Curated specification for contextual atmospheric backgrounds, subtle gradients, and high-impact telemetry. Atmospheric backgrounds behave as page-level or section-level visual environments, never as component-level decoration.',
    componentRef: 'special-treatments',
    approvedRules: [
      'Formalized as a Special Visual Treatment: Page-level or section-level visual environments, never decorative elements attached to individual components',
      'Large soft blurred fields (blur 160–200px) with continuous organic diffusion, zero hard circular edges, and zero visible decorative circles',
      'Zero component-level clipping: atmospheric layer sits behind content (z-0); cards and sections sit on top without clipping gradients inside radii',
      'Approved Color Progression: LIME / GREEN (#AEF366, #26C76A) → BLUE (#5967F6, #3B49DF) → COOL BLUE-VIOLET (#7D72E8). Strictly zero fuchsia, pink, magenta, red, or warm hues',
      'Usage Guardrails: MAY be used for Hero/introductory moments, editorial surfaces, intelligence analysis, and key section transitions. PROHIBITED inside individual cards, behind dense dataviz, or as repetitive decoration',
      'One Visual Accent at a Time: Atmospheric fields sit at z-0 behind content without affecting layout, interactive targets, or text readability',
      'Client Brand Compatibility: Visual atmosphere remains controlled and neutral enough to accommodate any client brand palette (including red, orange, or yellow) without clashing',
    ],
  },
  {
    number: '18',
    id: 'component-matrix',
    title: 'Component Matrix',
    category: 'Components',
    status: 'roadmap',
    version: 'v1.0',
    description: 'Comprehensive cross-reference matrix mapping core components to surface contexts, sizes, density modes, and variants.',
  },
  {
    number: '19',
    id: 'presets',
    title: 'Presets & Themes',
    category: 'Tokens',
    status: 'roadmap',
    version: 'v1.0',
    description: 'Preconfigured token bundles and theme definitions for rapid product onboarding and cross-agency alignments.',
  },
  {
    number: '20',
    id: 'ai-guardrails',
    title: 'AI Guardrails & Slop Prevention',
    category: 'Governance',
    status: 'approved',
    version: 'v1.0',
    description: 'Defensive design rules preventing generic AI styling, excessive rounded pills, fake chat widgets, decorative noise, and Title Case generation.',
    approvedRules: [
      'Global Capitalization Guardrail: Prevent AI generation of Title Case in UI strings. Enforce sentence case as the default across all interface copy, protecting official proper nouns, brands, platforms, and acronyms (e.g. WPP Media, Creative Intelligence, Meta, YouTube, AI).',
      'Never introduce chatbots, assistants, or AI panels unless explicitly requested',
      'Pill geometry restricted exclusively to Primary Buttons, Tags, and Status Badges',
      'Anti-Slop Discipline: Zero decorative gradient circles inside components, zero fake chatbots, zero ornamental pill flood',
      'No speculative UI decoration without genuine operational function',
    ],
  },
  {
    number: '21',
    id: 'visual-qa',
    title: 'Visual QA & Verification',
    category: 'Governance',
    status: 'approved',
    version: 'v1.0',
    description: 'System audit checklist, capitalization audit protocols, cross-browser parity benchmarks, and release sign-off criteria.',
    approvedRules: [
      'Global Capitalization Audit Protocol: Verify zero Title Case violations across all views, product applications, and components. Ensure sentence case is applied uniformly to all headings, buttons, tabs, labels, and microcopy, validating that only official proper names, brands, and acronyms maintain capitalization.',
      'Audit Checklist: Verify that button copy, card titles, navigation items, form fields, and status indicators strictly employ sentence case (e.g., "View all results", "Explore creative", "Progreso del análisis").',
      'Cross-viewport contrast, accessibility (WCAG 2.1 AA/AAA), and visual regression testing across Light, Dark, and Featured contexts.',
    ],
  },
];
